### ISSUE TITLE
How to Train on High Resolution

### ISSUE THREAD

**Issue by NorthanX** [cuiaiyu/dressing-in-order#53]
Hi, thanks for the great work! I am curious about the results with high resolution, like 512*358, so I want to train by my own, but I am not so sure about how to change the training process. Could you please give me some advice?

**Comment by cuiaiyu** [comment]
Hi!

You can retrain the model with input in 512 by specifying ```--load_size 512``` or ```--crop_size 512``` (I forget which one). If you get any error saying dimension doesn't match, please fix the hard code (which gives the error) from ```256``` to the input argument ```opt.load_size```, otherwise the code should be runnable.

GFLA flownet is likely requiring some retraining to 512 as well, because GFLA is also trained at 256x256. I am not sure how robust GFLA is with input resolution, but 

I'm not sure if the performance would maintain the same, as this work is only tested with 256. Some related work in higher resolution that may be interesting are:

https://pose-with-style.github.io/
https://tryongan.github.io/tryongan/

**Comment by NorthanX** [comment]
Thank you for your advice! I will try with that.
